/* Custom type StaticList Struct */
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>

// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
typedef REPLACE_THIS_WITH_YOUR_STATIC_LIST_TYPE_DEFINITION STATIC_LIST_TYPE;

#define typename(x) _Generic((x),		/* Get the name of a type */					\
																						\
			_Bool: 0,				  unsigned char: 1,				\
			 char: 2,					 signed char: 3,				\
		short int: 4,		 unsigned short int: 11,	 		\
			  int: 5,					 unsigned int: 12,				\
		 long int: 6,		   unsigned long int: 13,	 		\
	long long int: 7, unsigned long long int: 14,	\
			float: 8,						 double: 10,				 		\
	  long double: 9,				   char *: 15,			\
		   void *: 16,				int *: 17,			\
		  default: 18)

typedef struct StaticLists {
	int num_elements;
	size_t size;
	STATIC_LIST_TYPE *array;
} __Custom__StaticList;

void _checkIndex(__Custom__StaticList *list, int index) {
	if (index > list->num_elements) {
		fprintf(stderr, "Index out of bounds. Exiting\n");
		exit(-1);
	}
}

void _checkAlloc(__Custom__StaticList *list) {
	if (list->array == NULL) {
		fprintf(stderr, "Memory allocation failed. Exiting\n");
		exit(-1);
	}
}

void _tryRealloc(__Custom__StaticList *list, int num_elements) {
	list->num_elements += num_elements;
	list->array = realloc(list->array, list->num_elements * list->size);
	_checkAlloc(list);
}

void initList(__Custom__StaticList *list, int num_elements) {
	list->num_elements = num_elements;
	list->size = sizeof(STATIC_LIST_TYPE);
	list->array = calloc(num_elements, list->size);

	_checkAlloc(list);
}

void initListAtValue(__Custom__StaticList *list, int num_elements, STATIC_LIST_TYPE value) {
	initList(list, num_elements);
	for (register int i = 0; i < num_elements; i++) {
		*(list->array + i) = value;
	}
}

void initListAtValues(__Custom__StaticList *list, int num_elements, STATIC_LIST_TYPE values[]) {
	initList(list, num_elements);
	for (register int i = 0; i < num_elements; i++) {
		*(list->array + i) = values[i];
	}
}

void insertValueAtIndex(__Custom__StaticList *list, STATIC_LIST_TYPE element, int index) {
	_checkIndex(list, index);
	_tryRealloc(list, 1);
	for (register int i = list->num_elements; i > index; i--) {
		*(list->array + i) = *(list->array + i - 1);
	}
	*(list->array + index) = element;
}

STATIC_LIST_TYPE getValueAtIndex(__Custom__StaticList *list, int index) {
	_checkIndex(list, index);
	STATIC_LIST_TYPE element = *(list->array + index);
	return element;
}

STATIC_LIST_TYPE removeValueAtIndex(__Custom__StaticList *list, int index) {
	_checkIndex(list, index);
	STATIC_LIST_TYPE removed = *(list->array + index);
	for (register int i = index; i < list->num_elements - 1; i++) {
		*(list->array + i) = *(list->array + i + 1);
	}
	_tryRealloc(list, -1);
	return removed;
}

void addValueAtEnd(__Custom__StaticList *list, STATIC_LIST_TYPE element) {
	_tryRealloc(list, 1);
	*(list->array + list->num_elements - 1) = element; // num_elements already increased
}

void addValuesAtEnd(__Custom__StaticList *list, STATIC_LIST_TYPE elements[], int num_elements) {
	int start_index = list->num_elements;
	_tryRealloc(list, num_elements);
	for (register int i = 0; i < num_elements; i++) {
		*(list->array + start_index + i) = elements[i];
	}
}

void printList(__Custom__StaticList *list) {
	/* Can only print the folowing types:
	 * char
	 * strings (arrays of char)
	 * signed char
	 * unsigned char
	 * short (short int, signed short, signed short int)
	 * unsigned short (unsigned short int)
	 * int (signed, signed int)
	 * long (long int, signed long, signed long int)
	 * long long (long long int, signed long long int)
	 * unsigned long (unsigned long int)
	 * unsigned long long (unsigned long long int)
	 * float
	 * double
	 * long double
	 * _Bool
	 * pointers to void, char & int
	 *
	 * for all other types, it will print them as integers
	 */

	// is the list empty ?
	if (list->num_elements == 0) {
		printf("The List is empty\n");
		return;
	}

	// get first element of the list
	STATIC_LIST_TYPE elem = getValueAtIndex(list, 0);

	// get the type name
	int type_ = typename(elem);

	char symbol[6];
	if (type_ == 0) { // _Bool
		strcpy(symbol, "%d");
	} else if (type_ == 1) { // unsigned char
		strcpy(symbol, "%uc");
	} else if (type_ < 4) { // char + signed char
		strcpy(symbol, "%c");
	} else if (type_ < 8) { // signed char
		strcpy(symbol, "%lld");
	} else if (type_ < 11) { // float + double + long double
		strcpy(symbol, "%llf");
	} else if (type_ < 15) { // unsigned (short int, int, long int, long long int)
		strcpy(symbol, "%llu");
	} else if (type_ < 18) { // pointer to (void, int, char)
		strcpy(symbol, "%x");
	} else if (type_ == 18) { // other
		// printf("Type not found. Using default \%d\n");
		strcpy(symbol, "%d");
	} else {
		fprintf(stderr, "Invalid type integer: %d. Exiting\n", type_);
		exit(EXIT_FAILURE);
	}

	char str[] = "List[%d] = ";
	strcat(str, symbol);
	strcat(str, "\n");

	// if nothing is found, print as an int anyway
	for (int i = 0; i < list->num_elements; i++) {
		printf(str, i, *(list->array + i));
	}
}
